config/routes.rb
Chowdy::Application.routes.draw do

  get "oauths/oauth"
  get "oauths/callback"
  
  root to: 'user_sessions#new'
  post "user_sessions/create"
  get "user_sessions/destroy"
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  post 'customers/create' => 'customers#create', as: 'create_customer'
  post 'customers/failed_invoice' => 'customers#fail', as: 'failed_invoice'
  post 'customers/payment' => 'customers#payment', as: 'payment'
  post 'customers/submit_meal_rating' => 'customers#rate_menu_item', as: 'submit_meal_rating'
  post 'customers/update/:id' => 'customers#update', as: 'update_customer'
  post 'customers/submit_photo' => 'customers#photo_submission', as: 'meal_photo_submission'
  get 'customers/:id/create_profile' => 'customers#create_profile', as: 'create_customer_profile'
  get 'customers/:id/resend_confirmation_email_form' => 'customers#resend_confirmation_email_form', as: 'resend_confirmation_email_form'
  get 'customers/:id/resend_sign_up_link_form' => 'customers#resend_sign_up_link_form', as: 'resend_sign_up_link_form'
  get 'customers/:id/olrestart/:reminder_id' => 'customers#one_link_restart', as: 'one_link_restart'
  get 'customers/:id/add_to_do_not_email/:reminder_id' => 'customers#add_to_do_not_email', as: 'add_to_do_not_email'
  post 'customers/:id/resend_sign_up_link' => 'customers#resend_sign_up_link', as: 'resend_sign_up_link'
  post 'customers/:id/resend_signup_confirmation_email' => 'customers#resend_signup_confirmation_email', as: 'resend_signup_confirmation_email'
  get 'customers/resend_sign_up_link' => 'customers#resend_sign_up_link_customer_request', as: 'resend_sign_up_link_customer_request'
  get 'customers/view_submitted_photos' => 'customers#view_submitted_photos', as: 'customer_view_submitted_photos'
  
  
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'user/profile' => 'users#profile', as: 'user_profile'
  get 'admin_action/customer_sheet' => 'admin_actions#customer_sheet', as: 'customer_sheet'
  get 'admin_action/deliveries_csv' => 'admin_actions#delivery_csv', as: 'deliveries_csv'
  get 'admin_action/next_week_breakdown' => 'admin_actions#next_week_breakdown', as: 'next_week_breakdown'
  get 'admin_action/customer/:id/edit' => 'admin_actions#individual_customer_edit', as: 'admin_edit_customer'
  put 'admin_action/customer/:id/update' => 'admin_actions#individual_customer_update', as: 'admin_update_customer'
  get 'admin_action/failed_invoice/:id/mark_as_paid' => 'admin_actions#mark_failed_invoice_as_paid', as: 'mark_failed_invoice_as_paid'
  get 'admin_action/impersonate_user/:id' => 'admin_actions#impersonate', as: 'impersonate_user'
  get 'admin_action/get_user_activity/:id' => 'admin_actions#get_user_activity', as: 'get_user_activity'
  post 'admin_action/search_customer' => 'admin_actions#search_customer', as: 'search_customer'
  get  'admin_action/load_photo_submissions' => 'admin_actions#load_photo_submissions', as:'load_photo_submissions'
  put  'admin_action/toggle_photo_submission' => 'admin_actions#toggle_photo_submission', as:'toggle_photo_submission'
  get  'admin_action/:id/show_submitted_photo' => 'admin_actions#show_submitted_photo', as:'show_submitted_photo'
  post  'admin_action/make_photo_submission_selection' => 'admin_actions#make_photo_submission_selection', as:'make_photo_submission_selection'

  get  'partner_product_sales/weekly_sales_total_report' => 'partner_product_sales#weekly_sales_total_report', as: 'weekly_marketplace_totals'
  get  'partner_product_sales/weekly_sales_report' => 'partner_product_sales#weekly_sales_report', as: 'weekly_marketplace_deliveries'
  post 'partner_product_sales/search_order_by_customer' => 'partner_product_sales#search_order_by_customer', as: 'search_order_by_customer'
  post 'partner_product_sales/search_order_details_by_id' => 'partner_product_sales#search_order_details_by_id', as: 'search_order_details_by_id'
  get 'partner_product_sales/view_orders' => 'partner_product_sales#view_orders', as: 'view_orders'
  get 'partner_product_sales/edit_order' => 'partner_product_sales#edit_order', as: 'edit_order'
  put 'partner_product_sales/update_order' => 'partner_product_sales#update_order', as: 'update_order'
  get 'partner_product_sales/cancel_order' => 'partner_product_sales#cancel_order', as: 'cancel_order'
  get 'partner_product_sales/intro' => 'partner_product_sales#intro', as: 'marketplace_intro'
  put 'partner_product_sales/update_delivery_date' => 'partner_product_sales#update_delivery_date', as: 'update_order_delivery_date'
  put 'partner_product_sales/refund' => 'partner_product_sales#refund', as: 'order_refund'

  
  

  post 'partner_product_sales/order' => 'partner_product_sales#order', as: 'order_partner_product'

  post 'meal_selection/update' => 'meal_selections#update', as:'update_meal_choice'
  get  'meal_selections/view' => 'meal_selections#view_selection', as:'view_meals_selection'

  resources :password_resets
  resources :system_settings
  resources :vendors
  resources :partner_products
  get  'partner_product/paginate' => 'partner_products#paginate', as:'paginate_partner_products'
  get  'partner_product/:id/remove_photos' => 'partner_products#remove_photos', as:'remove_partner_product_photos'

  resources :scheduled_tasks
  resources :menus, only: [:update, :show]
  get 'menu/:id/pull_rating_details' => 'menus#pull_rating_details', as: 'pull_rating_details'
  get 'menu/pull_suggestion' => 'menus#pull_suggestion', as: 'pull_suggestion'
  get 'menu/pull_individual_detail' => 'menus#pull_individual_detail', as: 'pull_individual_detail'
  get 'menu/:id/edit_nutritional_info' => 'menus#edit_nutritional_info', as: 'edit_nutritional_info'
  get 'menu/:id/show_nutritional_info' => 'menus#show_nutritional_info', as: 'show_nutritional_info'
  post 'menu/:id/update_nutritional_info' => 'menus#update_nutritional_info', as: 'update_nutritional_info'
  post 'menu/copied_menu_nutritional_update' => 'menus#copied_menu_nutritional_update', as: 'copied_menu_nutritional_update'
  get 'scheduled_task/:id/run' => 'scheduled_tasks#run', as: 'run_task'

  get 'announcement/new' => 'system_settings#new_announcement', as: 'new_announcement'
  post 'announcement/create' => 'system_settings#create_announcement', as: 'create_announcement'
  resources :promotions
  put 'promotions/:id/activate' => 'promotions#activate', as: 'activate_promotion'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'start_date/edit' => 'start_dates#edit', as: 'edit_start_date'
  put 'start_date/update' => 'start_dates#update', as: 'update_start_date'

  get 'partner_product_delivery_dates/edit' => 'partner_product_delivery_dates#edit', as: 'edit_partner_product_delivery_date'
  put 'partner_product_delivery_dates/update' => 'partner_product_delivery_dates#update', as: 'update_partner_product_delivery_date'

  post 'redeem_promo' => 'promotion_redemptions#redeem', as: 'redeem_promo'

  get 'gifts/:id/view_redemption' => 'gifts#view_redemption', as: 'view_redemption'
  get 'gifts/:id/resend_sender_confirmation_form' => 'gifts#resend_sender_confirmation_form', as: 'resend_sender_confirmation_form'
  get 'gifts/:id/resend_recipient_confirmation_form' => 'gifts#resend_recipient_confirmation_form', as: 'resend_recipient_confirmation_form'
  post 'gifts/:id/resend_sender_confirmation' => 'gifts#resend_sender_confirmation', as: 'resend_sender_confirmation'
  post 'gifts/:id/resend_recipient_confirmation' => 'gifts#resend_recipient_confirmation', as: 'resend_recipient_confirmation'

  match '/:id' => "shortener/shortened_urls#show", via: [:get]

end

app/models/partner_product.rb
class PartnerProduct < ActiveRecord::Base
    belongs_to :vendor
    has_many :partner_product_sale_details
    has_many :partner_product_order_summaries, foreign_key: :product_id, primary_key: :id

    mount_uploaders :photos, PartnerProductUploader #for uploading multiple files, this has to be mount_uploaders insteat of mount_uploader

    acts_as_list

    def self.products_to_display
        PartnerProduct.find_by_sql("Select a.* From partner_products a left join partner_product_order_summaries b on a.id = b.product_id and b.delivery_date = '#{PartnerProductDeliveryDate.first.delivery_date}' where coalesce(b.ordered_quantity,0) < a.max_quantity and a.available = true Order By a.position asc, a.created_at desc")
    end

end

app/controllers/partner_products_controller.rb
class PartnerProductsController < ApplicationController
    

    def index
        @vendor = Vendor.where(id: params[:vendor_id]).take
        @vendor_products = @vendor.partner_products.order(created_at: :asc)

        respond_to do |format|
          format.html {
            render partial: 'table'
          }
        end      
    end


    def show
      @partner_product = PartnerProduct.find(params[:id])
      @photos = @partner_product.photos
      @disable_markplace_purchase =  SystemSetting.where(setting:"marketplace",setting_attribute:"order").blank? ? true : (SystemSetting.where(setting:"marketplace",setting_attribute:"order").take.setting_value == "true" ? false : true)
      respond_to do |format|
        format.html {
          render partial: 'show'
        }
      end
    end

    def paginate
      @parter_products = Kaminari.paginate_array(PartnerProduct.products_to_display).page(params[:page])
      @page = params[:page]
      @parter_products_menu = @parter_products.map{|pp| {product_id:pp.id, price:pp.price_in_cents, name:pp.product_name, description:pp.product_description}}
      @disable_markplace_purchase =  SystemSetting.where(setting:"marketplace",setting_attribute:"order").blank? ? true : (SystemSetting.where(setting:"marketplace",setting_attribute:"order").take.setting_value == "true" ? false : true)

      respond_to do |format|
        format.js {
          render partial: 'paginate'
        }
      end
    end


    def new
        @vendor = Vendor.where(id: params[:vendor_id]).take
        @partner_product = @vendor.partner_products.new
        @method = "POST"

        respond_to do |format|
          format.html {
            render partial: 'form'
          }
        end  
    end

    def create
        vendor = Vendor.where(id:params[:partner_product][:vendor_id]).take
        partner_product = vendor.partner_products.new(partner_product_params)
        partner_product.photos = params[:photos].values unless params[:photos].blank?

        if partner_product.save

          if params[:partner_product][:position].blank? 
            partner_product.insert_at(1)
          elsif params[:partner_product][:position].to_i == -1
            partner_product.move_to_bottom
          else 
            partner_product.insert_at(params[:partner_product][:position].to_i)
          end
          
          status = "success"
          notice_partner_product = "Partner product created"
        else
          status = "fail"
          notice_partner_product = "Parner product could not be created: #{partner_product.errors.full_messages.join(", ")}"
        end 

        respond_to do |format|
          format.json {
            render json: {status:status, message:notice_partner_product}
          } 
        end 
    end

    def edit
        @edit = true
        @method = "PUT"
        @vendor = Vendor.where(id: params[:vendor_id]).take
        @partner_product = PartnerProduct.find(params[:id])
        @photos_exist = @partner_product.photos?
        @photos = @partner_product.photos
        respond_to do |format|
          format.html {
            render partial: 'form'
          }
        end    
    end

    def update
        partner_product = PartnerProduct.where(id:params[:id]).take
        partner_product.assign_attributes(partner_product_params)
        partner_product.photos = params[:photos].values unless params[:photos].blank?

        if partner_product.save

          if params[:partner_product][:position].blank? 
            partner_product.insert_at(1)
          elsif params[:partner_product][:position].to_i == -1
            partner_product.move_to_bottom
          else 
            partner_product.insert_at(params[:partner_product][:position].to_i)
          end

          status = "success"
          notice_partner_product = "Partner product updated"
        else
          status = "fail"
          notice_partner_product = "Partner product could not be updated: #{partner_product.errors.full_messages.join(", ")}"
        end

        respond_to do |format|
          format.json {
            render json: {status:status, message:notice_partner_product}
          } 
        end         
    end

    def remove_photos
      partner_product = PartnerProduct.find(params[:id])
      partner_product.remove_photos!
      if partner_product.save
        status = "success"
        notice_partner_product = "Photos successfully removed"
      else
        status = "fail"
        notice_partner_product = "Photos could not be removed: #{partner_product.errors.full_messages.join(', ')}"
      end

        respond_to do |format|
          format.json {
            render json: {status:status, message:notice_partner_product}
          }   
        end    
    end

    def destroy
        partner_product = PartnerProduct.find(params[:id])
        if partner_product.destroy
          flash[:status] = "success"
          flash[:notice_partner_products] = "Partner product deleted"
        else
          flash[:status] = "fail"
          flash[:notice_partner_products] = "Partner product could not be deleted: #{vendor.errors.full_messages.join(", ")}"
        end

        redirect_to user_profile_path+"#partner_products"        
    end

    private

    def partner_product_params
      params.require(:partner_product).permit(:vendor_id,:product_id,:product_name,:product_description,:product_size,:vendor_product_sku,:vendor_product_upc,:cost_in_cents,:suggested_retail_price_in_cents,:price_in_cents,:max_quantity,:available)
    end


end

app/helpers/partner_products_helper.rb
module PartnerProductsHelper
end

app/views/partner_products/_form.html.erb
<script>
  
      function formRetrievalAjax() {      // this block of code is copy and pasted form _admin because this is required to run in the modal but modal can't access the function in the main _admin code
          $('.pull_system_setting_form, .pull_next_week_total, .nestedForm').off("click").on("click",function(){
            event.preventDefault();
            $.ajax({
              url: $(this).attr('href'),
              type: 'GET',
              dataType: 'html'
            }).done(function(data){
              $('#formModal .modal-content').html(data);
              $('#formModal').modal({show:true});
              $("#formModal").animate({
                  scrollTop: 0
              }, 500);

              formRetrievalAjax();
            });
          });
      };  

      $('#partner-product-creation input[required=required]').off('keyup').on('keyup',check_required_fields)

      function check_required_fields () {
        if ($('#partner-product-creation input[required=required]').filter(function(){return $(this).val() == "" }).length == 0) {
          $('.form_submit_add_product').removeClass('disabled');
        }  else {
          $('.form_submit_add_product').addClass('disabled');
        }
      };

      function updateWithoutFile() {

            var submitButton = $(".form_submit_add_product")

            var submit_button_original_value = submitButton.attr('value');
            var submit_button_width = submitButton.outerWidth();

            $.ajax({
              url: $('#partner-product-creation').attr('action'),
              type: '<%= @method %>',
              data: $('#partner-product-creation').serialize(),
              dataType: 'JSON'
            }).done(function(data){

              if(data.status == "success"){
                $('#partner-product-creation').find('.alert').html(data.message);
                $('#partner-product-creation').find('.alert').removeClass('alert-success').removeClass('alert-danger').addClass('alert-success').removeClass('hidden');
                $('#partner-product-creation').find('.form_submit_add_product').removeClass('disabled').attr('value',submit_button_original_value);

              $.ajax({
                url: "<%= partner_products_path+'?vendor_id='+@vendor.id.to_s %>",
                type: 'GET',
                dataType: 'html'
              }).done(function(data){
                $('#formModal .modal-content').html(data);
                $('#formModal').modal({show:true});
                $("#formModal").animate({
                    scrollTop: 0
                }, 500);

                formRetrievalAjax();
              });

              } else {
                $('#partner-product-creation').find('.alert').html(data.message);
                $('#partner-product-creation').find('.alert').removeClass('alert-success').removeClass('alert-danger').addClass('alert-danger').removeClass('hidden');
                $('#partner-product-creation').find('.form_submit_add_product').removeClass('disabled').attr('value',submit_button_original_value);
              }      

            })        
      }

    // drop zone  
    function configureDropZone() {
        Dropzone.options.partnerProductCreation = {
          url: $('#partner-product-creation').attr('action'),
          paramName: 'photos',
          autoProcessQueue: false,
          uploadMultiple: true,
          parallelUploads: 100,
          maxFiles: 5,
          maxFilesize: 0.5, // MB
          forceFallback: false,
          acceptedFiles: 'image/jpg,image/jpeg,image/png',
          dictDefaultMessage: "<i class='fa fa-cloud-upload'> Click or drag and drop up to 5 images here (JPG or PNG files only, up to 0.5MB per file)",
          init: function() {
                myDropzone = this; // closure

            var submitButton = $(".form_submit_add_product")

            var submit_button_original_value = submitButton.attr('value');
            var submit_button_width = submitButton.outerWidth();

            submitButton.off("click").on("click", function(event) {
              if(event.preventDefault) {
                event.preventDefault();
                submitButton.css('width',submit_button_width);
                submitButton.addClass('disabled').attr('value','Wait...');
              } else {
                event.returnValue = false;
                submitButton.css('width',submit_button_width);
                submitButton.addClass('disabled').attr('value','Wait...');
              };

              if (myDropzone.getQueuedFiles().length > 0) {                        
                  myDropzone.processQueue();  
              } else {                       
                  updateWithoutFile();
              }         

            });
            // this is the hover effect
            this.on('dragover', function(){
                $('.upload .dropzone').addClass('draghover');
            });
            this.on('dragleave', function(){
                $('.upload .dropzone').removeClass('draghover');
            }); 
            this.on('drop',function(){
                $('.upload .dropzone').removeClass('draghover');
                $('.dz-default.dz-message').html("");
            });
            // spinner when file is uploading
            this.on('sending',function(){
                $('.dz-default.dz-message').html("<i class='fa fa-circle-o-notch fa-2x upload spinner'></i>");
            });
            this.on('removedfile',function(){
                $('.dz-default.dz-message').html("<i class='fa fa-cloud-upload'> Drop your logo here or click to upload");
            });
            this.on('success',function(file, data){

                if(data.status == "success"){
                  $('#partner-product-creation').find('.alert').html(data.message);
                  $('#partner-product-creation').find('.alert').removeClass('alert-success').removeClass('alert-danger').addClass('alert-success').removeClass('hidden');
                  $('#partner-product-creation').find('.form_submit_add_product').removeClass('disabled').attr('value',submit_button_original_value);

                $.ajax({
                  url: "<%= partner_products_path+'?vendor_id='+@vendor.id.to_s %>",
                  type: 'GET',
                  dataType: 'html'
                }).done(function(data){
                  $('#formModal .modal-content').html(data);
                  $('#formModal').modal({show:true});
                  $("#formModal").animate({
                      scrollTop: 0
                  }, 500);

                  formRetrievalAjax();
                });

                } else {
                  $('#partner-product-creation').find('.alert').html(data.message);
                  $('#partner-product-creation').find('.alert').removeClass('alert-success').removeClass('alert-danger').addClass('alert-danger').removeClass('hidden');
                  $('#partner-product-creation').find('.form_submit_add_product').removeClass('disabled').attr('value',submit_button_original_value);
                }              

            });
          }
        };
    }


    $('#remove_photo_inner').off('click').on('click',function(){
      event.preventDefault();
      $.ajax({
        url: $(this).attr('href'),
        type: 'GET',
        dataType: 'JSON'
      }).done(function(data){
        if (data.status == "success") {
          $('.delete_after_photo_removal').remove();
          $('div.dz-default.dz-message').show();
          $('div.dz-default.dz-message').appendTo('div.ajax_uploader label');          
        } else {
          alert(data.notice_partner_product);
        }
      });      
    });

</script>



<%= form_for @partner_product, html: {class: "dropzone", multipart:true, id:"partner-product-creation", style:"border:none; border-radius: 5px;"} do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Partner Product</h4>
  </div>
  <div class="modal-body">
    <div class="form-group" style="cursor:pointer;">
        <%= f.label :product_name, "Product Name (required)", style:"cursor:pointer;" %>
        <%= f.text_field :product_name, class: "form-control", required: true, style:"cursor:text;"  %>
    </div>
    <div class="form-group">
        <%= f.label :product_description, "Product Description (required)", style:"cursor:pointer;" %>
        <%= f.text_field :product_description, class: "form-control", required: true, style:"cursor:text;"  %>
    </div>
    <div class="form-group">
        <%= f.label :product_size, "Product Size (required)", style:"cursor:pointer;" %>
        <%= f.text_field :product_size, class: "form-control", required: true, style:"cursor:text;"  %>
    </div>
    <div class="form-group">
        <%= f.label :price_in_cents, "Price in Cents (required)", style:"cursor:pointer;" %>
        <%= f.text_field :price_in_cents, class: "form-control", required: true, style:"cursor:text;" %>
    </div>
    <div class="form-group">
        <%= f.label :vendor_product_sku, "Vendor's Product SKU / Internal ID", style:"cursor:pointer;" %>
        <%= f.text_field :vendor_product_sku, class: "form-control", style:"cursor:text;" %>
    </div>
    <%= f.hidden_field :vendor_id, value: @vendor.id %>
    <div class="form-group">
        <%= f.label :vendor_product_upc, "Product UPC", style:"cursor:pointer;" %>
        <%= f.text_field :vendor_product_upc, class: "form-control", style:"cursor:text;"  %>
    </div>
    <div class="form-group">
        <%= f.label :cost_in_cents, "Unit cost to Chowdy in Cents (required)", style:"cursor:pointer;" %>
        <%= f.text_field :cost_in_cents, class: "form-control",required: true, style:"cursor:text;" %>
    </div>
    <div class="form-group">
        <%= f.label :suggested_retail_price_in_cents, "Vendor suggested retail price (this is not the actual price customers see)", style:"cursor:pointer;" %>
        <%= f.text_field :suggested_retail_price_in_cents, class: "form-control", style:"cursor:text;" %>
    </div>
    <div class="form-group">
        <%= f.label :max_quantity, "Max Weekly Units (required)", style:"cursor:pointer;" %>
        <%= f.number_field :max_quantity, class: "form-control", required: true, style:"cursor:text;" %>
    </div>
    <div class="form-group">
        <%= f.label :available, 'Show on Marketplace?' %>
        <% if @edit %>
          <%= f.check_box :available, class: "form-control" %>
        <% else %>
          <%= f.check_box :available, class: "form-control", checked:true %>
        <% end %>
    </div>
    <div class="form-group">
        <%= f.label :position, 'Position on marketplace (blank will be placed first, -1 will be placed last)' %>
        <%= f.number_field :position, class: "form-control", style:"cursor:text;", min:"-1" %>
    </div>  
    <div class="form-group html_photo_uploader hidden">
        <%= f.label :photos %>
        <%= f.file_field :photos, class: "form-control", multiple:true %>
    </div>
    <div class="form-group ajax_uploader">
      <label>Product photos <% if @photos_exist %><span class="delete_after_photo_removal">(<a id="remove_photo_inner" href="<%= remove_partner_product_photos_path(@partner_product) %>" style="cursor:pointer;">remove all photos</a>)</span><% end %></label><br>
        <% if @photos_exist %>
          <section class="delete_after_photo_removal">
            <% @photos.each do |p| %>
              <%= image_tag p.thumb.url, size:"150x100", class:"m-r-sm" %>
            <% end %>
          </section>
        <% end %>
    </div>
    <div class="alert m-t-xs m-b-xs hidden">
    </div>
    <% if @edit %>
      <%= link_to "Delete This Product", partner_product_path(@partner_product), method: :delete, style:"cursor:pointer;" %>
    <% end %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-md btn-default m-t-sm" data-dismiss="modal" style="cursor:pointer;">Close</button>
    <button type="button" class="btn btn-md btn-default m-t-sm nestedForm" href="<%= partner_products_path+'?vendor_id='+@vendor.id.to_s %>" style="min-width: 0px; cursor:pointer;">Back</button>
    <% if @edit %>
      <%= f.submit class: "btn btn-md btn-default m-t-sm form_submit_add_product ", style:"cursor:pointer;" %>
    <% else %>
      <%= f.submit class: "btn btn-md btn-default m-t-sm form_submit_add_product disabled", style:"cursor:pointer;" %>
    <% end %>
  </div>
<% end %>
<script>  
configureDropZone(); 
Dropzone.discover();
<% if @photos_exist %>
  $('div.dz-default.dz-message').hide();
<% else %>
  $('div.dz-default.dz-message').appendTo('div.ajax_uploader label');
<% end %>
</script>

app/views/partner_products/_paginate_content.html.erb
<div class="row m-b-md" >
  <div class="col-l-md-12" style="width:100%">
    <div style="background-image:url('https://s3.amazonaws.com/toronto-chowdy/marketplace-banner.jpg'); background-size:contain; background-repeat:no-repeat; width:100%; padding-bottom:17%;">
    <a href="<%= view_orders_path %>" class="pull-right" id="view_order_history" style="color:white; font-weight: bold; margin-right:20px; margin-top:10px;">View Order History</a>
      <div class="row padder">
        <div class="alert alert-success hidden" style="margin-bottom:0 !important;font-size: 18px;" id="partner_product_success_alert">
        </div>
      </div> 
    </div>
  </div>
</div>
<div class="row padder m-t-none">
    <% partner_products.each do |pp| %>
      <div class="col-lg-2 col-md-2 col-sm-5 col-xs-5 m-l-none m-b-sm m-r-md hovereffect" style="width:300px; height: 200px; padding:0; border-radius:5px; overflow:hidden; z-index:2;">
          <img class="img-responsive" src="<%= pp.photos[0].thumb.url if pp.photos[0] %>" alt="" style=" width:300px;max-width:300px;">
          <div class="overlay">
             <h2 style="text-transform:none;"><%= pp.product_name %></h2>
             <section class="info">
                <section class="content">
                  <p>by <%= pp.vendor.vendor_name %> ($<%= (pp.price_in_cents.to_f / 100).round(2).to_s %> + HST)</p>
                  <p><%= pp.product_description[0...60] + (pp.product_description.length > 60 ? "..." : "") %> <a class="pull_modal" href="<%= partner_product_path(pp) %>">more</a></p>
                  <form class="add_to_cart" data-product-id="<%= pp.id %>" style="color:black">
                    <div class="form-group">
                      <input type="number" class="qty" data-product-id="<%= pp.id %>" required="true" placeholder="Qty" min="0" style="width:60px;height:32px; float:left; margin-left: 32px; margin-right: 10px; border:1px solid white; text-align: center;" <% if disable_markplace_purchase %>disabled="disabled"<% end %>>
                    </div>
                    <input type="submit" class="btn btn-s-md btn-default" style="float:left; border: none; border-radius: 0px; color:white !important; background-color:#f0ad4e;" value="Add to Cart" <% if disable_markplace_purchase %>disabled="disabled"<% end %>>
                  </form>
                </section>
             </section>
          </div>
      </div>
    <% end %>
</div>
<div class="row padder m-t-none">
  <%= paginate Kaminari.paginate_array(PartnerProduct.products_to_display).page(page), params: {controller: :partner_products, action: :paginate} %>
</div>