config/routes.rb
Chowdy::Application.routes.draw do

  get "oauths/oauth"
  get "oauths/callback"
  
  root to: 'user_sessions#new'
  post "user_sessions/create"
  get "user_sessions/destroy"
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  post 'customers/create' => 'customers#create', as: 'create_customer'
  post 'customers/failed_invoice' => 'customers#fail', as: 'failed_invoice'
  post 'customers/payment' => 'customers#payment', as: 'payment'
  post 'customers/submit_meal_rating' => 'customers#rate_menu_item', as: 'submit_meal_rating'
  post 'customers/update/:id' => 'customers#update', as: 'update_customer'
  post 'customers/submit_photo' => 'customers#photo_submission', as: 'meal_photo_submission'
  get 'customers/:id/create_profile' => 'customers#create_profile', as: 'create_customer_profile'
  get 'customers/:id/resend_confirmation_email_form' => 'customers#resend_confirmation_email_form', as: 'resend_confirmation_email_form'
  get 'customers/:id/resend_sign_up_link_form' => 'customers#resend_sign_up_link_form', as: 'resend_sign_up_link_form'
  get 'customers/:id/olrestart/:reminder_id' => 'customers#one_link_restart', as: 'one_link_restart'
  get 'customers/:id/add_to_do_not_email/:reminder_id' => 'customers#add_to_do_not_email', as: 'add_to_do_not_email'
  post 'customers/:id/resend_sign_up_link' => 'customers#resend_sign_up_link', as: 'resend_sign_up_link'
  post 'customers/:id/resend_signup_confirmation_email' => 'customers#resend_signup_confirmation_email', as: 'resend_signup_confirmation_email'
  get 'customers/resend_sign_up_link' => 'customers#resend_sign_up_link_customer_request', as: 'resend_sign_up_link_customer_request'
  get 'customers/view_submitted_photos' => 'customers#view_submitted_photos', as: 'customer_view_submitted_photos'
  
  
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'user/profile' => 'users#profile', as: 'user_profile'
  get 'admin_action/customer_sheet' => 'admin_actions#customer_sheet', as: 'customer_sheet'
  get 'admin_action/deliveries_csv' => 'admin_actions#delivery_csv', as: 'deliveries_csv'
  get 'admin_action/next_week_breakdown' => 'admin_actions#next_week_breakdown', as: 'next_week_breakdown'
  get 'admin_action/customer/:id/edit' => 'admin_actions#individual_customer_edit', as: 'admin_edit_customer'
  put 'admin_action/customer/:id/update' => 'admin_actions#individual_customer_update', as: 'admin_update_customer'
  get 'admin_action/failed_invoice/:id/mark_as_paid' => 'admin_actions#mark_failed_invoice_as_paid', as: 'mark_failed_invoice_as_paid'
  get 'admin_action/impersonate_user/:id' => 'admin_actions#impersonate', as: 'impersonate_user'
  get 'admin_action/get_user_activity/:id' => 'admin_actions#get_user_activity', as: 'get_user_activity'
  post 'admin_action/search_customer' => 'admin_actions#search_customer', as: 'search_customer'
  get  'admin_action/load_photo_submissions' => 'admin_actions#load_photo_submissions', as:'load_photo_submissions'
  put  'admin_action/toggle_photo_submission' => 'admin_actions#toggle_photo_submission', as:'toggle_photo_submission'
  get  'admin_action/:id/show_submitted_photo' => 'admin_actions#show_submitted_photo', as:'show_submitted_photo'
  post  'admin_action/make_photo_submission_selection' => 'admin_actions#make_photo_submission_selection', as:'make_photo_submission_selection'

  get  'partner_product_sales/weekly_sales_total_report' => 'partner_product_sales#weekly_sales_total_report', as: 'weekly_marketplace_totals'
  get  'partner_product_sales/weekly_sales_report' => 'partner_product_sales#weekly_sales_report', as: 'weekly_marketplace_deliveries'
  post 'partner_product_sales/search_order_by_customer' => 'partner_product_sales#search_order_by_customer', as: 'search_order_by_customer'
  post 'partner_product_sales/search_order_details_by_id' => 'partner_product_sales#search_order_details_by_id', as: 'search_order_details_by_id'
  get 'partner_product_sales/view_orders' => 'partner_product_sales#view_orders', as: 'view_orders'
  get 'partner_product_sales/edit_order' => 'partner_product_sales#edit_order', as: 'edit_order'
  put 'partner_product_sales/update_order' => 'partner_product_sales#update_order', as: 'update_order'
  get 'partner_product_sales/cancel_order' => 'partner_product_sales#cancel_order', as: 'cancel_order'
  get 'partner_product_sales/intro' => 'partner_product_sales#intro', as: 'marketplace_intro'
  put 'partner_product_sales/update_delivery_date' => 'partner_product_sales#update_delivery_date', as: 'update_order_delivery_date'
  put 'partner_product_sales/refund' => 'partner_product_sales#refund', as: 'order_refund'

  
  

  post 'partner_product_sales/order' => 'partner_product_sales#order', as: 'order_partner_product'

  post 'meal_selection/update' => 'meal_selections#update', as:'update_meal_choice'
  get  'meal_selections/view' => 'meal_selections#view_selection', as:'view_meals_selection'

  resources :password_resets
  resources :system_settings
  resources :vendors
  resources :partner_products
  get  'partner_product/paginate' => 'partner_products#paginate', as:'paginate_partner_products'
  get  'partner_product/:id/remove_photos' => 'partner_products#remove_photos', as:'remove_partner_product_photos'

  resources :scheduled_tasks
  resources :menus, only: [:update, :show]
  get 'menu/:id/pull_rating_details' => 'menus#pull_rating_details', as: 'pull_rating_details'
  get 'menu/pull_suggestion' => 'menus#pull_suggestion', as: 'pull_suggestion'
  get 'menu/pull_individual_detail' => 'menus#pull_individual_detail', as: 'pull_individual_detail'
  get 'menu/:id/edit_nutritional_info' => 'menus#edit_nutritional_info', as: 'edit_nutritional_info'
  get 'menu/:id/show_nutritional_info' => 'menus#show_nutritional_info', as: 'show_nutritional_info'
  post 'menu/:id/update_nutritional_info' => 'menus#update_nutritional_info', as: 'update_nutritional_info'
  post 'menu/copied_menu_nutritional_update' => 'menus#copied_menu_nutritional_update', as: 'copied_menu_nutritional_update'
  get 'scheduled_task/:id/run' => 'scheduled_tasks#run', as: 'run_task'

  get 'announcement/new' => 'system_settings#new_announcement', as: 'new_announcement'
  post 'announcement/create' => 'system_settings#create_announcement', as: 'create_announcement'
  resources :promotions
  put 'promotions/:id/activate' => 'promotions#activate', as: 'activate_promotion'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'start_date/edit' => 'start_dates#edit', as: 'edit_start_date'
  put 'start_date/update' => 'start_dates#update', as: 'update_start_date'

  get 'partner_product_delivery_dates/edit' => 'partner_product_delivery_dates#edit', as: 'edit_partner_product_delivery_date'
  put 'partner_product_delivery_dates/update' => 'partner_product_delivery_dates#update', as: 'update_partner_product_delivery_date'

  post 'redeem_promo' => 'promotion_redemptions#redeem', as: 'redeem_promo'

  get 'gifts/:id/view_redemption' => 'gifts#view_redemption', as: 'view_redemption'
  get 'gifts/:id/resend_sender_confirmation_form' => 'gifts#resend_sender_confirmation_form', as: 'resend_sender_confirmation_form'
  get 'gifts/:id/resend_recipient_confirmation_form' => 'gifts#resend_recipient_confirmation_form', as: 'resend_recipient_confirmation_form'
  post 'gifts/:id/resend_sender_confirmation' => 'gifts#resend_sender_confirmation', as: 'resend_sender_confirmation'
  post 'gifts/:id/resend_recipient_confirmation' => 'gifts#resend_recipient_confirmation', as: 'resend_recipient_confirmation'

  match '/:id' => "shortener/shortened_urls#show", via: [:get]

end

app/controllers/admin_actions_controller.rb
class AdminActionsController < ApplicationController

    def impersonate
        user = User.find(params[:id])
        impersonate_user(user)
        redirect_to user_profile_path
    end

    def toggle_photo_submission
        toggle = params[:toggle]

        if toggle == "off"
            @display = false
            if SystemSetting.where(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers").blank?
                SystemSetting.create(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers",setting_value:"false")
            else 
                SystemSetting.where(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers").take.update_attributes(setting_value:"false")
            end
        elsif toggle == "on"
            @display = true
            if SystemSetting.where(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers").blank?
                SystemSetting.create(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers",setting_value:"true")
            else 
                SystemSetting.where(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers").take.update_attributes(setting_value:"true")
            end
        end

        respond_to do |format|
          format.html {
            render partial: 'toggle_photo_submission'
          }      
        end
    end

    def load_photo_submissions
      @show_photo_submission_to_customers = SystemSetting.where(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers").blank? ? false : (SystemSetting.where(setting:"photo_submission",setting_attribute:"show_photo_submission_to_customers").take.setting_value == "true" ? true : false)
      @photo_submissions = PhotoSubmission.order(created_at: :desc).page(params[:page]).per(6)

        respond_to do |format|
          format.html {
            render partial: 'load_photo_submissions'
          }      
        end
    end

    def show_submitted_photo
        @photo = PhotoSubmission.where(id:params[:id]).take

        
        respond_to do |format|
          format.html {
            render partial: 'show_submitted_photo'
          }
        end
    end

    def make_photo_submission_selection
        status_array = []
        params['_json'].each do |selection|
            photo_id = selection['id'].to_i
            decision = selection['chosen']
            photo_submitted = PhotoSubmission.where(id:photo_id).take
            
            if photo_submitted
                if decision #this basically means only update if the photo is selected, which means admin cannot unchoose a photo after it has been chosen
                    begin 
                        unless photo_submitted.paid?
                            customer = photo_submitted.customer
                            credit_amount = customer.price_increase_2015? ? 903 : 790
                            photo_submitted.customer.add_discount_to_stripe(credit_amount,"1 meal credit for photo submission being chosen: #{photo_submitted.photo.url}"[0...255])
                            meals_earned = customer.meals_earned_from_photo_submission.to_i + 1 
                            customer.update_attributes(meals_earned_from_photo_submission:meals_earned)
                        end
                    rescue => error
                        status_array.push({status:false,message:"Meal credit for photo #{photo_id} could not be attached: #{error.message}"})
                    else
                        if photo_submitted.update_attributes(selected:decision)
                            unless photo_submitted.paid?
                                photo_submitted.update_attributes(paid:true,date_selected:Date.today)
                            end
                            status_array.push({status:true})
                        else
                            status_array.push({status:false,message:"Photo #{photo_id} could not be updated: #{photo_submitted.errors.full_messages.join(", ")}"})
                        end
                    end
                else
                    if photo_submitted.selected?
                        status_array.push({status:true,message:"You cannot unselect photo #{photo_id}"})
                    end
                end
            else
                status_array.push({status:false,message:"Photo #{photo_id} does not exist"})
            end
        end

        issues = status_array.select{|sa| sa[:status] == false}
        if issues.length > 0
            status = "fail"
            message = "Some photos could not be updated. #{issues.map{|a| a[:message]}.join('; ')}"
        else
            status = "success"
            message = "Successfully saved and credits applied. #{status_array.map{|a| a[:message]}.join(' ')}"
        end

        respond_to do |format|
          format.json {
            render json: {status:status, message:message}
          } 
        end
    end

    def search_customer
        keyword = params[:keyword]
        show_everything = params[:show_everything] == "true" ? true : false

        @result = show_everything ? Customer.all.order(created_at: :desc) : Customer.search_by_all(keyword)

        @customer_column_names = [] #make sure this section is identical to what's in users controller

            @customer_column_names.push("email")
            @customer_column_names.push("name")
            @customer_column_names.push("active?")
            @customer_column_names.push("paused?")
            @customer_column_names.push("recurring_delivery")
            @customer_column_names.push("first_pick_up_date")
            @customer_column_names.push("next_pick_up_date")
            @customer_column_names.push("monday_pickup_hub")
            @customer_column_names.push("thursday_pickup_hub")
            @customer_column_names.push("monday_delivery_hub")
            @customer_column_names.push("thursday_delivery_hub")
            @customer_column_names.push("total_meals_per_week")
            @customer_column_names.push("regular_meals_on_monday")
            @customer_column_names.push("regular_meals_on_thursday")
            @customer_column_names.push("green_meals_on_monday")
            @customer_column_names.push("green_meals_on_thursday")
            @customer_column_names.push("referral")
            @customer_column_names.push("referral_code")
            @customer_column_names.push("matched_referrers_code")
            @customer_column_names.push("sponsored")
            @customer_column_names.push("pause_end_date")
            @customer_column_names.push("raw_green_input")
            @customer_column_names.push("hub")
            @customer_column_names.push("created_at")


        respond_to do |format|
          format.html {
            render partial: 'customer_list_row'
          }      
        end  
        
    end

    def customer_sheet  
        current_pick_up_date = SystemSetting.where(setting:"system_date", setting_attribute:"pick_up_date").take.setting_value.to_date
        production_day_sunday = Chowdy::Application.closest_date(-1,7,current_pick_up_date)
        production_day_wednesday = Chowdy::Application.closest_date(1,3,current_pick_up_date)

        @beef_monday = Menu.where(production_day:production_day_sunday, meal_type:"Beef").take.meal_name unless Menu.where(production_day:production_day_sunday, meal_type:"Beef").blank?
        @beef_thursday = Menu.where(production_day:production_day_wednesday, meal_type:"Beef").take.meal_name unless Menu.where(production_day:production_day_wednesday, meal_type:"Beef").blank?
        @pork_monday = Menu.where(production_day:production_day_sunday, meal_type:"Pork").take.meal_name unless Menu.where(production_day:production_day_sunday, meal_type:"Pork").blank?
        @pork_thursday = Menu.where(production_day:production_day_wednesday, meal_type:"Pork").take.meal_name unless Menu.where(production_day:production_day_wednesday, meal_type:"Pork").blank?
        @poultry_monday = Menu.where(production_day:production_day_sunday, meal_type:"Poultry").take.meal_name unless Menu.where(production_day:production_day_sunday, meal_type:"Poultry").blank?
        @poultry_thursday = Menu.where(production_day:production_day_wednesday, meal_type:"Poultry").take.meal_name unless Menu.where(production_day:production_day_wednesday, meal_type:"Poultry").blank?
        @salad_bowl_1_monday = Menu.where(production_day:production_day_sunday, meal_type:"Salad Bowl 1").take.meal_name unless Menu.where(production_day:production_day_sunday, meal_type:"Salad Bowl 1").blank?
        @salad_bowl_1_thursday = Menu.where(production_day:production_day_wednesday, meal_type:"Salad Bowl 1").take.meal_name unless Menu.where(production_day:production_day_wednesday, meal_type:"Salad Bowl 1").blank?
        @salad_bowl_2_monday = Menu.where(production_day:production_day_sunday, meal_type:"Salad Bowl 2").take.meal_name unless Menu.where(production_day:production_day_sunday, meal_type:"Salad Bowl 2").blank?
        @salad_bowl_2_thursday = Menu.where(production_day:production_day_wednesday, meal_type:"Salad Bowl 2").take.meal_name unless Menu.where(production_day:production_day_wednesday, meal_type:"Salad Bowl 2").blank?
        @diet_monday = Menu.where(production_day:production_day_sunday, meal_type:"Diet").take.meal_name unless Menu.where(production_day:production_day_sunday, meal_type:"Diet").blank?
        @diet_thursday = Menu.where(production_day:production_day_wednesday, meal_type:"Diet").take.meal_name unless Menu.where(production_day:production_day_wednesday, meal_type:"Diet").blank?
        @chefs_special_monday = Menu.where(production_day:production_day_sunday, meal_type:"Chef's Special").take.meal_name unless Menu.where(production_day:production_day_sunday, meal_type:"Chef's Special").blank?

app/helpers/admin_actions_helper.rb
module AdminActionsHelper

end

app/views/admin_actions/_customer_list_row.html.erb
<% @result.each do |s| %>
  <tr>
    <td><button class="btn btn-s-md btn-warning btn-rounded pull_system_setting_form" href="<%= admin_edit_customer_path(s) %>" style="min-width: 0px;width: 60px;">Edit</button></td>
    <td><%= link_to "Stripe", "https://dashboard.stripe.com/customers/#{s.stripe_customer_id}", target: "_blank", class:"btn btn-s-md btn-primary btn-rounded", style:"min-width: 0px;width: 60px;" %></td>
    <td><%= s.user.blank? ? "No" : (s.user.facebook_email.blank? ? "Yes" : "Yes - FB") %></td>
    <td><button class="btn btn-s-md btn-warning btn-rounded pull_system_setting_form" href="<%= resend_sign_up_link_form_path(s) %>" style="min-width: 0px;width: 60px;">Send</button></td>
    <td><button class="btn btn-s-md btn-warning btn-rounded pull_system_setting_form" href="<%= resend_confirmation_email_form_path(s) %>" style="min-width: 0px;width: 60px;">Send</button></td>
    <td><%= s.formatted_request_queues %></td>
    <% @customer_column_names.each do |c| %>
      <td><%= s.send(c.to_sym) %></td>
    <% end %>
  </tr>
<% end %>

app/views/admin_actions/_form.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Next week's meals breakdown</h4>
  </div>
  <div class="modal-body">
      <!-- <div class="panel panel-default"> -->
        <div class="table-responsive text-center">
          <table class="display table table-striped m-b-none" style="font-size: 12px">
            <thead>
              <tr>
                <th></th>
                <th>Monday</th>
                <th>Thursday</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Regular (Non-selected)</td>
                <td><%= @regular_monday %></td>
                <td><%= @regular_thursday %></td>
              </tr>
              <tr>
                <td>Green (Non-selected)</td>
                <td><%= @green_monday %></td>
                <td><%= @green_thursday %></td>
              </tr>
              <tr>
                <td>Beef Selected </td>
                <td><%= @selected_beef_next_monday %></td>
                <td><%= @selected_beef_next_thursday %></td>
              </tr>
              <tr>
                <td>Poultry Selected </td>
                <td><%= @selected_poultry_next_monday %></td>
                <td><%= @selected_poultry_next_thursday %></td>
              </tr>
              <tr>
                <td>Pork Selected </td>
                <td><%= @selected_pork_next_monday %></td>
                <td><%= @selected_pork_next_thursday %></td>
              </tr>
              <tr>
                <td>Salad Bowl 1 Selected </td>
                <td><%= @selected_salad_bowl_1_next_monday %></td>
                <td><%= @selected_salad_bowl_1_next_thursday %></td>
              </tr>
              <tr>
                <td>Salad Bowl 2 Selected </td>
                <td><%= @selected_salad_bowl_2_next_monday %></td>
                <td><%= @selected_salad_bowl_2_next_thursday %></td>
              </tr>
              <tr>
                <td>Diet Selected </td>
                <td><%= @selected_diet_next_monday %></td>
                <td><%= @selected_diet_next_thursday %></td>
              </tr>
              <tr>
                <td>Chef's Special Selected </td>
                <td><%= @selected_chefs_special_next_monday %></td>
                <td><%= @selected_chefs_special_next_thursday %></td>
              </tr>
              <tr>
                <td>Green 1 Selected </td>
                <td><%= @selected_green_1_next_monday %></td>
                <td><%= @selected_green_1_next_thursday %></td>
              </tr>
              <tr>
                <td>Green 2 Selected </td>
                <td><%= @selected_green_2_next_monday %></td>
                <td><%= @selected_green_2_next_thursday %></td>
              </tr>
              <tr>
                <td>Pork adjustment (Non-selected)</td>
                <td><%= @neg_adjustment_pork_next_monday %></td>
                <td><%= @neg_adjustment_pork_next_thursday %></td>
              </tr>
              <tr>
                <td>Beef adjustment (Non-selected)</td>
                <td><%= @neg_adjustment_beef_next_monday %></td>
                <td><%= @neg_adjustment_beef_next_thursday %></td>
              </tr>
              <tr>
                <td>Poultry adjustment (Non-selected)</td>
                <td><%= @neg_adjustment_poultry_next_monday %></td>
                <td><%= @neg_adjustment_poultry_next_thursday %></td>
              </tr>
              <tr>
                <td>Wanda's</td>
                <td><%= @monday_wandas %></td>
                <td><%= @thursday_wandas %></td>
              </tr>
              <tr>
                <td>Coffee Bar</td>
                <td><%= @monday_coffee_bar %></td>
                <td><%= @thursday_coffee_bar %></td>
              </tr>
              <tr>
                <td>deKEFIR</td>
                <td><%= @monday_dekefir %></td>
                <td><%= @thursday_dekefir %></td>
              </tr>
              <tr>
                <td>The Red Bench</td>
                <td><%= @monday_red_bench %></td>
                <td><%= @thursday_red_bench %></td>
              </tr>
              <tr>
                <td>The Green Grind</td>
                <td><%= @monday_green_grind %></td>
                <td><%= @thursday_green_grind %></td>
              </tr>
              <tr>
                <td>Unassigned</td>
                <td><%= @monday_unassigned %></td>
                <td><%= @thursday_unassigned %></td>
              </tr>
            </tbody>
          </table>
        </div>
      <!-- </div>      -->
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-md btn-default m-t-sm" data-dismiss="modal">Close</button>
  </div>

app/views/admin_actions/_get_user_activity.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">User account activity
      (<a type="button" class="nestedForm" href="<%= admin_edit_customer_path(@user.customer) %>" style="min-width: 0px;">back to edit</a>)
    </h4>
  </div>
  <div class="modal-body">
    <table id="rating_details_table" class="display table table-striped m-b-none" style="font-size: 12px;">
      <thead>
        <tr>
          <th >Date and Time</th>
          <th >Activity</th>
        </tr>
      </thead>
      <tbody>
        <% @activites.each do |activity| %>
          <tr>
            <td><%= activity.created_at.strftime("%A %Y-%m-%d %I:%M %p ") %></td>
            <td><%= activity.activity_type %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
 
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-md btn-default m-t-sm nestedForm" href="<%= admin_edit_customer_path(@user.customer) %>" style="min-width: 0px;">Back to Edit Customer</button>
    <button type="button" class="btn btn-md btn-default m-t-sm" data-dismiss="modal">Close</button>
    
  </div>

app/views/admin_actions/_load_photo_submissions.html.erb
<div class="row">
    <div class="col sm-12 padder">
        <span id="display_photo_submission_toggle_button_container">
            <% if @show_photo_submission_to_customers %>
                <button type="button" class="btn btn-md btn-warning m-t-none toggle_photo_submission_button"  href="<%= toggle_photo_submission_path+'?toggle=off' %>">Hide photo submission from customers</button>
            <% else %>
                <button type="button" class="btn btn-md btn-success m-t-none toggle_photo_submission_button" href="<%= toggle_photo_submission_path+'?toggle=on' %>">Make photo submission visible to customers</button>
            <% end %>
        </span>
    </div>
</div>
<div class="row" style="height: 50px;">
    <div class="col-sm-5">
        <button type="button" id="submit_photo_selections" href="<%= make_photo_submission_selection_path %>" class="btn btn-md btn-info m-t-sm disabled">Submit Selection (this will trigger meal credits instantly)</button>
    </div>    
    <div class="col-sm-7">
        <div id="photo_submission_alert" class="alert alert-block text-center hidden" style="margin-bottom: 0px;">

        </div>        
    </div>
</div>
<br>

<div class="row">
    <table class="display table table-striped m-b-none" style="font-size: 12px;">
        <thead>
            <tr>
                <th>ID</th>
                <th>Photo</th>
                <th>Date Submitted<br>(Date chosen by admin in parenthesis)</th>
                <th>Caption</th>
                <th>Customer Name<br>Email</th>
                <th>Customer Social Media Handles</th>
                <th>Selected?</th>
            </tr>
        </thead>
        <tbody>
            <% @photo_submissions.each do |ps| %>

                
                    <tr>
                        <td>
                            <%= ps.id %>
                        </td>
                        <td>
                          <a href="<%= show_submitted_photo_path(ps) %>" class="pull_modal" >
                            <img class="img-responsive" src="<%= ps.photo.url %>" alt="Photo is missing" style=" width:150;max-width:150;">  
                          </a>
                        </td>
                        <td>
                            <%= ps.created_at.strftime("%b %e, %Y") %>
                            <% unless ps.date_selected.blank? %>
                                <br>
                                (<%= ps.date_selected.strftime("%b %e, %Y") %>)
                            <% end %>
                        </td>
                        <td>
                            <%= ps.caption %>
                        </td>
                        <td>
                            <%= ps.customer.name %><br> 
                            <%= ps.customer.email %>
                        </td>
                        <td>
                            <%= ps.customer.social_media_handles %>
                        </td>
                        <td>
                            <%= check_box_tag :selected,ps.id,ps.selected?,class: "form-control photo_submission_selection_checkbox", disabled: ps.selected? %>
                        </td>
                    </tr>
            <% end %>
        </tbody>
    </table>
</div>


<div class="row padder m-t-none">
  <%= paginate @photo_submissions, params: {controller: :admin_actions, action: :load_photo_submissions} %>
</div>

<script>

    
    $('.photo_submission_selection_checkbox').on('click',function(){
        $('#submit_photo_selections').removeClass('disabled');
    })

        function toggle_display_to_customers() {
            $('.toggle_photo_submission_button').off('click').on('click',function(){
                $.ajax({
                  url: $(this).attr('href'),
                  type: 'PUT',
                  dataType: 'HTML'
                }).done(function(data){
                    $('#display_photo_submission_toggle_button_container').html(data);
                    toggle_display_to_customers();
                });
            })
        }

        toggle_display_to_customers();

        function submit_selection() {
            var submission_array = [];
            $('.photo_submission_selection_checkbox').each(function(){
                submission_array.push({id:$(this).val(),chosen:$(this).is(':checked')})
            })

            var submit_button_width = $('#submit_photo_selections').outerWidth();
            var submit_button_original_value = $('#submit_photo_selections').html();
            $('#submit_photo_selections').css('width',submit_button_width).addClass('disabled').html('Wait...');

            $.ajax({
              url: $(this).attr('href'),
              type: 'POST',
              data: JSON.stringify(submission_array),
              contentType: "application/json",
              dataType: 'JSON'
            }).done(function(data){
                if (data.status == "success") {
                    $('#photo_submission_alert').removeClass("alert-danger").removeClass("alert-success").addClass("alert-success").html(data.message).removeClass('hidden');
                        $('#submit_photo_selections').html(submit_button_original_value);
                        $('#submit_photo_selections').addClass("disabled");
                } else {
                    $('#photo_submission_alert').removeClass("alert-danger").removeClass("alert-success").addClass("alert-danger").html(data.message).removeClass('hidden');
                }
                
            });

        }

        $('#submit_photo_selections').on('click',submit_selection);


</script>

app/views/admin_actions/_toggle_photo_submission.html.erb
<% if @display %>
<button type="button" class="btn btn-md btn-warning m-t-none toggle_photo_submission_button"  href="<%= toggle_photo_submission_path+'?toggle=off' %>">Hide photo submission from customers</button>
<% else %>
<button type="button" class="btn btn-md btn-success m-t-none toggle_photo_submission_button" href="<%= toggle_photo_submission_path+'?toggle=on' %>">Make photo submission visible to customers</button>
<% end %>