config/routes.rb
Chowdy::Application.routes.draw do

  get "oauths/oauth"
  get "oauths/callback"
  
  root to: 'user_sessions#new'
  post "user_sessions/create"
  get "user_sessions/destroy"
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  post 'customers/create' => 'customers#create', as: 'create_customer'
  post 'customers/failed_invoice' => 'customers#fail', as: 'failed_invoice'
  post 'customers/payment' => 'customers#payment', as: 'payment'
  post 'customers/submit_meal_rating' => 'customers#rate_menu_item', as: 'submit_meal_rating'
  post 'customers/update/:id' => 'customers#update', as: 'update_customer'
  post 'customers/submit_photo' => 'customers#photo_submission', as: 'meal_photo_submission'
  get 'customers/:id/create_profile' => 'customers#create_profile', as: 'create_customer_profile'
  get 'customers/:id/resend_confirmation_email_form' => 'customers#resend_confirmation_email_form', as: 'resend_confirmation_email_form'
  get 'customers/:id/resend_sign_up_link_form' => 'customers#resend_sign_up_link_form', as: 'resend_sign_up_link_form'
  get 'customers/:id/olrestart/:reminder_id' => 'customers#one_link_restart', as: 'one_link_restart'
  get 'customers/:id/add_to_do_not_email/:reminder_id' => 'customers#add_to_do_not_email', as: 'add_to_do_not_email'
  post 'customers/:id/resend_sign_up_link' => 'customers#resend_sign_up_link', as: 'resend_sign_up_link'
  post 'customers/:id/resend_signup_confirmation_email' => 'customers#resend_signup_confirmation_email', as: 'resend_signup_confirmation_email'
  get 'customers/resend_sign_up_link' => 'customers#resend_sign_up_link_customer_request', as: 'resend_sign_up_link_customer_request'
  get 'customers/view_submitted_photos' => 'customers#view_submitted_photos', as: 'customer_view_submitted_photos'
  
  
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'user/profile' => 'users#profile', as: 'user_profile'
  get 'admin_action/customer_sheet' => 'admin_actions#customer_sheet', as: 'customer_sheet'
  get 'admin_action/deliveries_csv' => 'admin_actions#delivery_csv', as: 'deliveries_csv'
  get 'admin_action/next_week_breakdown' => 'admin_actions#next_week_breakdown', as: 'next_week_breakdown'
  get 'admin_action/customer/:id/edit' => 'admin_actions#individual_customer_edit', as: 'admin_edit_customer'
  put 'admin_action/customer/:id/update' => 'admin_actions#individual_customer_update', as: 'admin_update_customer'
  get 'admin_action/failed_invoice/:id/mark_as_paid' => 'admin_actions#mark_failed_invoice_as_paid', as: 'mark_failed_invoice_as_paid'
  get 'admin_action/impersonate_user/:id' => 'admin_actions#impersonate', as: 'impersonate_user'
  get 'admin_action/get_user_activity/:id' => 'admin_actions#get_user_activity', as: 'get_user_activity'
  post 'admin_action/search_customer' => 'admin_actions#search_customer', as: 'search_customer'
  get  'admin_action/load_photo_submissions' => 'admin_actions#load_photo_submissions', as:'load_photo_submissions'
  put  'admin_action/toggle_photo_submission' => 'admin_actions#toggle_photo_submission', as:'toggle_photo_submission'
  get  'admin_action/:id/show_submitted_photo' => 'admin_actions#show_submitted_photo', as:'show_submitted_photo'
  post  'admin_action/make_photo_submission_selection' => 'admin_actions#make_photo_submission_selection', as:'make_photo_submission_selection'

  get  'partner_product_sales/weekly_sales_total_report' => 'partner_product_sales#weekly_sales_total_report', as: 'weekly_marketplace_totals'
  get  'partner_product_sales/weekly_sales_report' => 'partner_product_sales#weekly_sales_report', as: 'weekly_marketplace_deliveries'
  post 'partner_product_sales/search_order_by_customer' => 'partner_product_sales#search_order_by_customer', as: 'search_order_by_customer'
  post 'partner_product_sales/search_order_details_by_id' => 'partner_product_sales#search_order_details_by_id', as: 'search_order_details_by_id'
  get 'partner_product_sales/view_orders' => 'partner_product_sales#view_orders', as: 'view_orders'
  get 'partner_product_sales/edit_order' => 'partner_product_sales#edit_order', as: 'edit_order'
  put 'partner_product_sales/update_order' => 'partner_product_sales#update_order', as: 'update_order'
  get 'partner_product_sales/cancel_order' => 'partner_product_sales#cancel_order', as: 'cancel_order'
  get 'partner_product_sales/intro' => 'partner_product_sales#intro', as: 'marketplace_intro'
  put 'partner_product_sales/update_delivery_date' => 'partner_product_sales#update_delivery_date', as: 'update_order_delivery_date'
  put 'partner_product_sales/refund' => 'partner_product_sales#refund', as: 'order_refund'

  
  

  post 'partner_product_sales/order' => 'partner_product_sales#order', as: 'order_partner_product'

  post 'meal_selection/update' => 'meal_selections#update', as:'update_meal_choice'
  get  'meal_selections/view' => 'meal_selections#view_selection', as:'view_meals_selection'

  resources :password_resets
  resources :system_settings
  resources :vendors
  resources :partner_products
  get  'partner_product/paginate' => 'partner_products#paginate', as:'paginate_partner_products'
  get  'partner_product/:id/remove_photos' => 'partner_products#remove_photos', as:'remove_partner_product_photos'

  resources :scheduled_tasks
  resources :menus, only: [:update, :show]
  get 'menu/:id/pull_rating_details' => 'menus#pull_rating_details', as: 'pull_rating_details'
  get 'menu/pull_suggestion' => 'menus#pull_suggestion', as: 'pull_suggestion'
  get 'menu/pull_individual_detail' => 'menus#pull_individual_detail', as: 'pull_individual_detail'
  get 'menu/:id/edit_nutritional_info' => 'menus#edit_nutritional_info', as: 'edit_nutritional_info'
  get 'menu/:id/show_nutritional_info' => 'menus#show_nutritional_info', as: 'show_nutritional_info'
  post 'menu/:id/update_nutritional_info' => 'menus#update_nutritional_info', as: 'update_nutritional_info'
  post 'menu/copied_menu_nutritional_update' => 'menus#copied_menu_nutritional_update', as: 'copied_menu_nutritional_update'
  get 'scheduled_task/:id/run' => 'scheduled_tasks#run', as: 'run_task'

  get 'announcement/new' => 'system_settings#new_announcement', as: 'new_announcement'
  post 'announcement/create' => 'system_settings#create_announcement', as: 'create_announcement'
  resources :promotions
  put 'promotions/:id/activate' => 'promotions#activate', as: 'activate_promotion'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'start_date/edit' => 'start_dates#edit', as: 'edit_start_date'
  put 'start_date/update' => 'start_dates#update', as: 'update_start_date'

  get 'partner_product_delivery_dates/edit' => 'partner_product_delivery_dates#edit', as: 'edit_partner_product_delivery_date'
  put 'partner_product_delivery_dates/update' => 'partner_product_delivery_dates#update', as: 'update_partner_product_delivery_date'

  post 'redeem_promo' => 'promotion_redemptions#redeem', as: 'redeem_promo'

  get 'gifts/:id/view_redemption' => 'gifts#view_redemption', as: 'view_redemption'
  get 'gifts/:id/resend_sender_confirmation_form' => 'gifts#resend_sender_confirmation_form', as: 'resend_sender_confirmation_form'
  get 'gifts/:id/resend_recipient_confirmation_form' => 'gifts#resend_recipient_confirmation_form', as: 'resend_recipient_confirmation_form'
  post 'gifts/:id/resend_sender_confirmation' => 'gifts#resend_sender_confirmation', as: 'resend_sender_confirmation'
  post 'gifts/:id/resend_recipient_confirmation' => 'gifts#resend_recipient_confirmation', as: 'resend_recipient_confirmation'

  match '/:id' => "shortener/shortened_urls#show", via: [:get]

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email].downcase, params[:password])
      redirect_to(user_profile_path, notice: 'Login successful')
    else
      if User.where(email:params[:email].downcase).length == 1
        if User.where(email:params[:email].downcase).take.facebook_email.blank?
          flash[:login_error] = "Incorrect password. Please try again"
        else 
          flash[:login_error] = "Please log in with Facebook"
        end
      else
        if Customer.where(email:params[:email].downcase).length > 0
          flash[:login_error] = "Please use the link in your confirmation email to create an account first. If you did not receive the confirmation email, <a href='#{resend_sign_up_link_customer_request_path+"?email="+params[:email].downcase}'>click here</a> to get the link sent to your email again"
        else
          flash[:login_error] = "Cannot find your subscription. You must <a href='http://chowdy.ca/signup'>sign up</a> for a subscription first to create an account"
        end
      end
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to(login_path, notice: 'Logged out')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<section id="content" class="wrapper-md" style="height: 100%; background-image: url(<%= asset_path 'chowdy-members.jpg' %>); background-size: cover;">    
    <div class="m-t-lg container aside-xl animated fadeInUp" style="max-width: 360px; background-color: white">
      <p class="navbar-brand block m-t-lg m-b-none" style="float:none !important;">
        <%= link_to "http://chowdy.ca" do %>
          <%= image_tag "logo-dark.png", width:"120px", alt: "Chowdy", class: "m-t-sm m-b-sm", id: "login_logo" %>
        <% end %>
      </p>
      <section class="m-b-lg">
        <header class="wrapper text-center" style="color:#788288">
          <strong>Log in to manage your subscription</strong>
        </header>
        <% if flash[:login_error] %>
          <div class="alert alert-<%= flash[:status] == "success" ? "success" : "danger" %>">
            <%= raw flash[:login_error] %>
          </div>
        <% end %>
        <%= form_tag user_sessions_create_path, :method => :post do %>
          <div class="list-group">
            <div class="list-group-item" style="border-color:#eaeef1">
              <%= text_field_tag :email,nil ,class:"form-control no-border", style:"border-color: transparent; border-width: 0; box-shadow: none;", placeholder: "Email" %>
            </div>
            <div class="list-group-item" style="border-color:#eaeef1">
               <%= password_field_tag :password,nil,class:"form-control no-border", style:"border-color: transparent; border-width: 0; box-shadow: none;", placeholder:"Password (case sensitive)" %>
            </div>
          </div>
          <%= submit_tag "Log in", class:"btn btn-lg btn-info btn-block", style:"border-radius: 2px" %>
          <div class="text-center m-t m-b"><%= link_to auth_at_provider_path(provider: :facebook), class: "btn btn-lg btn-primary btn-block", style:"border-radius: 2px" do %>
                <i class="fa fa-facebook pull-left"></i>
                <small>Log in with Facebook</small>
            <% end %></div>
          <div class="text-center m-t m-b"><a href="#" data-toggle="modal" data-target="#resetModal"><small>Forgot password?</small></a></div>
          <div class="text-center m-t m-b"><a href="http://chowdy.ca/signup"><small>This page is for members only. Click here to sign up for a subscription</small></a></div>
        <% end %>
      </section>
    </div>
</section>


<!-- Reset password modal -->
<div class="modal fade" id="resetModal" tabindex="-1" role="dialog" aria-labelledby="cancelModal" aria-hidden="true" style="z-index: 10000;">
  <div class="modal-dialog">
      <div class="modal-content">
        <%= form_tag password_resets_path, :method => :post do %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Type in your email to reset password</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <%= label_tag :email %>
              <%= text_field_tag :email,nil,class: "input-sm input-s form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag 'Reset password',class:"btn btn-primary" %>
          </div>
        <% end %>
      </div>
  </div>
</div>